### ISSUE TITLE
Provide the repository name of code snippet

### ISSUE THREAD

**Issue by JiyangZhang** [Leolty/repobench#1]
Hi, thanks for your great work. 

After checking the dataset, I found that there is no repository name for each example in the dataset. Is it possible that you could provide the repo name for the benchmark? Thank you!

**Comment by Leolty** [comment]
Hi there! Thank you for your feedback and for checking the dataset. I can definitely add the repository name for each example in the benchmark. It might take some time, but I'll make it a priority.

**Comment by Leolty** [comment]
> 

Hi, @JiyangZhang. Thanks again for your feedback. We have now added the `repo_name` attribute to every data point in the dataset. Please feel free to check it now.

Apologies for the oversight, and we appreciate your contribution in helping us improve the dataset. If you have any further questions or suggestions, please let us know.
