### ISSUE TITLE
Error when loading the V1.1 dataset from Huggingface

### ISSUE THREAD

**Issue by Symbolk** [Leolty/repobench#10]
Just running the load_dataset() reports the following error, how to solve it?

Traceback (most recent call last):
File "/home/workspace/x/repobench/repo_bench.py", line 6, in
dataset = load_dataset("tianyang/repobench_java_v1.1")
File "/root/miniconda3/envs/autocoder/lib/python3.10/site-packages/datasets/load.py", line 2582, in load_dataset
builder_instance.download_and_prepare(
File "/root/miniconda3/envs/autocoder/lib/python3.10/site-packages/datasets/builder.py", line 1005, in download_and_prepare
self._download_and_prepare(
File "/root/miniconda3/envs/autocoder/lib/python3.10/site-packages/datasets/builder.py", line 1118, in _download_and_prepare
verify_splits(self.info.splits, split_dict)
File "/root/miniconda3/envs/autocoder/lib/python3.10/site-packages/datasets/utils/info_utils.py", line 101, in verify_splits
raise NonMatchingSplitsSizesError(str(bad_splits))
datasets.utils.info_utils.NonMatchingSplitsSizesError: [{'expected': SplitInfo(name='cross_file_first', num_bytes=504528431, num_examples=8033, shard_lengths=None, dataset_name=None), 'recorded': SplitInfo(name='cross_file_first', num_bytes=670976719, num_examples=8722, shard_lengths=[8361, 361], dataset_name='repobench_java_v1.1')}, {'expected': SplitInfo(name='cross_file_random', num_bytes=467242455, num_examples=7618, shard_lengths=None, dataset_name=None), 'recorded': SplitInfo(name='cross_file_random', num_bytes=675950097, num_examples=8705, shard_lengths=[8353, 352], dataset_name='repobench_java_v1.1')}, {'expected': SplitInfo(name='in_file', num_bytes=488999100, num_examples=7910, shard_lengths=None, dataset_name=None), 'recorded': SplitInfo(name='in_file', num_bytes=674755454, num_examples=8696, shard_lengths=[8348, 348], dataset_name='repobench_java_v1.1')}]

**Comment by Leolty** [comment]
I guess this error may happen when using different versions of the datasets library.

To resolve this issue, you can pass the `ignore_verifications=True` parameter when calling `load_dataset()`. This will instruct the library to ignore the split size verification and proceed with loading the dataset.

Here's how you can modify your code:

```python
dataset = load_dataset("tianyang/repobench_java_v1.1", ignore_verifications=True)
```

Please give it a try and let me know if it resolves the issue for you.

**Comment by Symbolk** [comment]
> I guess this error may happen when using different versions of the datasets library.
> 
> To resolve this issue, you can pass the `ignore_verifications=True` parameter when calling `load_dataset()`. This will instruct the library to ignore the split size verification and proceed with loading the dataset.
> 
> Here's how you can modify your code:
> 
> ```python
> dataset = load_dataset("tianyang/repobench_java_v1.1", ignore_verifications=True)
> ```
> 
> Please give it a try and let me know if it resolves the issue for you.

Works like a charm, thanks!
