### ISSUE TITLE
Download the original repositories for constructing RepoBench

### ISSUE THREAD

**Issue by oceaneLIU** [Leolty/repobench#13]
Hi! We are doing some experiments based on RepoBench, but we're a little confused about how to obtain the original repositories for constructing each task. For example, we want to construct a sliding window based knowledge repo for each task, how do we get the whole repo files?

**Comment by Leolty** [comment]
As per your email request:

[Download Link](https://drive.google.com/file/d/12zvgxWpKNMLtNru8Vf1ZdH5t8RXdTniv/view?usp=sharing)

You can use this link to download the repositories with a knowledge cutoff of August 2023. (I'm not entirely sure if this is the final version; please contact me if there are any issues.)

To help reduce your debugging time, try to use the following method to load the file:

```python
import pandas as pd

file_path = '/PATH_TO_FILE/files_final.json.gz'
df = pd.read_json(file_path, compression='gzip', lines=True)
```
