### ISSUE TITLE
Inconsistent Newline Characters in Python Dataset Affecting Test Accuracy

### ISSUE THREAD

**Issue by HaomiaoPan** [Leolty/repobench#16]
I've encountered an issue while using the "tianyang/repobench_python_v1.1" and "tianyang/repobench_java_v1.1" datasets. The test accuracy for Python is significantly lower, and after multiple comparisons, I've identified the problem to be related to newline characters ("\n").

In the Python dataset, each entry in the "cropped_code" field ends with a newline character ("\n"), unlike the Java dataset. When using the `cropped_code()` function to construct prompts, the LLM receives two newline characters, which results in poor performance.

To address this, I suggest removing the trailing newline character ("\n") from the "cropped_code" field in each entry of the "tianyang/repobench_python_v1.1" dataset.

Here is the code I used:
```python
from datasets import load_dataset

python_dataset = load_dataset("tianyang/repobench_python_v1.1")
java_dataset = load_dataset("tianyang/repobench_java_v1.1", ignore_verifications=True)
setting = "cross_file_first"
python_dataset = python_dataset[setting]
java_dataset = java_dataset[setting]
for i in range(100):
    print(repr(python_dataset[i]["cropped_code"][-100:]))
    print(repr(java_dataset[i]["cropped_code"][-100:]))
    print("\n")
    print("----------------------------------------")
    print("\n")
    
```

Thank you for your attention to this matter.

**Comment by Leolty** [comment]
Apologies for the delayed response.

I would like to confirm if this issue is related to the following line:

https://github.com/Leolty/repobench/blob/bc7127f3c0b25840defcef353990c21502760570/data/utils.py#L31

This line appears to assume that there is no newline character at the end of `cropped_code` and adds a newline character at the very end.

**Comment by Leolty** [comment]
Ok!!  thanks for pointing this out i am fixing it now
