### ISSUE TITLE
评估代码中没有codebleu_score模块

### ISSUE THREAD

**Issue by sbyalx** [Leolty/repobench#18]
在eval.py中导入模块： from evaluation.metrics import exact_match_score, edit_similarity_score, codebleu_score
报错： ImportError: cannot import name 'codebleu_score' from 'evaluation.metrics'，查看了代码，在metrics.py中确实没有部分代码，请问这个怎么解决

**Comment by Leolty** [comment]
Hi,

我刚刚 push 了 CodeBLEU 的代码。你可能需要再安装以下几个packages：

```
pip install codebleu tree-sitter-python tree-sitter-java
```

我刚试了一下，发现 `tree-sitter-python` 安装时可能会下载失败，java是可以成功安装的。我不确定是否只是我这边的问题。根据[官方 repo](https://github.com/tree-sitter/py-tree-sitter)，这个命令应该是正确的。我暂时也没有在 issues 中找到类似的。

**Comment by sbyalx** [comment]
好的多谢，问题已解决
