### ISSUE TITLE
Question regarding evaluation on RepoBench-R

### ISSUE THREAD

**Issue by wasiahmad** [Leolty/repobench#2]
The Table 2 in the paper shows the results for the finetuned dense encoders? or they are directly evaluated on the RepoBench-R dataset? The codebase does not seem to have fineutning code for RepoBench-R using CodeBERT or CodeGen. Please correct me if I am wrong. Thanks!

**Comment by Leolty** [comment]
yeah you are right. We just added the training data for RepoBench-R several days ago, and in the paper, we just used semantic retrieval, instead of a trained classifier.

**Comment by wasiahmad** [comment]
In that case, how can I reproduce the UniXCoder number of Table 2? Is there any script for the evaluation?

**Comment by Leolty** [comment]
So, in the paper, we kept `3` lines for retrieval, you can run:

```bash
python run_retriever.py \
    --language python \
    --model_name microsoft/unixcoder-base \
    --max_length 512 \
    --similarity cosine \
    --keep_lines [3]
   ```

This will give you 2 `json` files under `results/retrieval/unixcoder-base`:
- `results/retrieval/unixcoder-base/python_first.json`
- `results/retrieval/unixcoder-base/python_random.json`

The result format will be like

```JSONC
{
  "easy": [
      {
      "3": [2, 0, 4, 5, 1], \\ Top 5 ranked
      "ground_truth": 0
      },
      {
      \\ ...
      }
   ],
  "hard": [
     \\ ...
]
}
```

Then you can run 
```bash
python evaluation/evaluate.py --file_path results/retrieval/unixcoder-base/python_first.json
```

This will give you the `acc@k`. I clone the repo and run the first 100 for easy and the first 100 for hard, with the following script, here is what I got:

```
Easy Level, 3 lines lept, acc@1: 32.00, acc@3: 62.00
Hard Level, 3 lines lept, acc@1: 19.00, acc@3: 46.00, acc@5: 61.00
```
