### ISSUE TITLE
release of the original repositories

### ISSUE THREAD

**Issue by wasiahmad** [Leolty/repobench#3]
Does the dataset released as part of this work include the original repositories? I saw the completion datasets include augmented prompts. So, I am guessing original repositories are not released. If this is the case, is it possible to release the original repositories? It will be helpful to foster future research.

**Comment by Leolty** [comment]
Do you mean just the original repos (like all the files including the repos), with no masking?

**Comment by JiyangZhang** [comment]
I have a similar question. Could you provide the version of github-code dataset you used to create repobench?
It seems github-code updated their data

**Comment by Leolty** [comment]
@JiyangZhang  The original github-code dataset is really large, but I can share a subset with each repo containing 32 to 128 files (~4G) aggregated by `repository name`.

**Comment by Leolty** [comment]
Yes, right, this is the version we used (I downloaded the data ~5 months ago, I think the latest update of the data is ~1 year ago). As mentioned in paper, this data is stored in file-level, we aggregate all the files by repo-level.

**Comment by JiyangZhang** [comment]
Hi,

Thanks for the clarification. Could you also share the script to extract data from github-code dataset? I found some mismatch between repobench data and github-code, e.g. there is some missing space or newline between these two sources.

Thanks

**Comment by Leolty** [comment]
Hi Jiyang,

I apologize for not addressing your inquiry earlier. It seems that the entire script is quite complex, and I'm currently unable to allocate time to organize it properly.

Regarding the issue with spaces and newlines, could you please clarify if you are referring to the characters `/t` or `/n` specifically? Thank you for bringing this to my attention. It's possible that I made some small mistakes in parsing, and I apologize for any confusion caused.

If the issue pertains only to the newline character (`/n`), I believe (and hope) it shouldn't significantly affect generation, matching, or other functionalities. However, problems related to the tab character (`\t`) can be more severe. To better understand the issue, could you provide some examples?
