### ISSUE TITLE
The candidate code snippets for retrieval

### ISSUE THREAD

**Issue by oceaneLIU** [Leolty/repobench#6]
Hi,

I'm little confused about the candidate code snippets for retrieval. In the paper, it is said that "(2) Lexical Retrieval uses Jaccard Similarity and Edit Similarity to assess the relevance between the cropped code from the in-file context and the candidate code snippets.". So what are the candidate code snippets exactly?

By looking into the test dataset, I found that for each completion case stored in dict format, there is a key called 'context' with at most 9 code snippets. Is this the retrieval source?

**Comment by Leolty** [comment]
Do u mean the retrieval part or the completion part?

I think you are using the `easy` subset (5~9 candidates) of `repobench-r`. For the retrieval, we use `acc@k` to evaluate, which means the task is to rank the contexts (for easy it is at most 9), one of which is the gold context (will be use for next line prediction).

The candidate code snippets are the code list (`context`).

**Comment by oceaneLIU** [comment]
Thanks a lot for your reply! I'm actually looking into the retrieval part.

**Comment by Leolty** [comment]
Sounds great. Then you are right, the context key, which should correspond to a list, should be the retrieval source. And there should be a `gold_snippet_idx` (iirc, or maybe `gold_snippet_index`), that is the one should be retrieved.

**Comment by oceaneLIU** [comment]
Get, thanks a lot for your explanation!
