### ISSUE TITLE
Question regarding evaluation on RepoBench-R 

### ISSUE THREAD

**Issue by xmwenxincheng** [Leolty/repobench#8]
Great work, thank you for sharing your source code. I was wondering if you could provide the code for RepoBench-R using CodeBERT? It seems like the repository currently doesn't include it.

**Comment by chao-peng** [comment]
By the way, could the authors also provide the code for RepoBench-R using tree-sitter? It also seems like the repository doesn't include it.

**Comment by Leolty** [comment]
> Great work, thank you for sharing your source code. I was wondering if you could provide the code for RepoBench-R using CodeBERT? It seems like the repository currently doesn't include it.


Hi there,

Thank you for reaching out. To run RepoBench-R using CodeBERT, you can indeed use the `microsoft/codebert-base` model. Here's how you can do it:

```bash
python run_repobench_r.py \
    --language python \
    --similarity cosine \
    --keep_lines 3 \
    --model_name microsoft/codebert-base \
    --max_length 512
```

If you encounter any issues or bugs while doing this, please don't hesitate to let me know.

**Comment by Leolty** [comment]
> By the way, could the authors also provide the code for RepoBench-R using tree-sitter? It also seems like the repository doesn't include it.

Im always trying to work on organizing this part of code, but it's not quite ready for release yet. Are you interested in a newer version of the dataset? I just built recent ones available and can share them.

**Comment by xmwenxincheng** [comment]
Great! Thanks a lot for your reply!

**Comment by chao-peng** [comment]
> > By the way, could the authors also provide the code for RepoBench-R using tree-sitter? It also seems like the repository doesn't include it.
> 
> Im always trying to work on organizing this part of code, but it's not quite ready for release yet. Are you interested in a newer version of the dataset? I just built recent ones available and can share them.

We are trying to build a dataset from our internal repos. Thank you for your reply! Look forward to the release of the code.
